from docsie_universal_importer.providers.base import StorageTreeView, ImporterView
from .import_provider import GoogleCloudStorageProvider

storage_view = StorageTreeView.provider_view(GoogleCloudStorageProvider)
importer_view = ImporterView.provider_view(GoogleCloudStorageProvider)
